/*
 * Copyright (c) 2026 Tenstorrent AI ULC
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef GRENDEL_NOC2AXI_DATA_H
#define GRENDEL_NOC2AXI_DATA_H

#include "grendel_noc2axi.h"

static const struct gr_noc2axi_mask_entry gr_noc2axi_mask_entries[] = {
	/* idx  0: Athena Config           0x0_0010_0000_0000 */
	{
		.bar = 0x0,
		.compare = 0x1000000000ULL,
		.mask = 33,
		.ep_id_size = 1,
		.ep_idx = 32,
		.table_offset = 16,
		.translate_addr = true,
		.initialized = true,
		.index = 0,
	},
	/* idx  1: Keraunos Config         0x0_0012_0000_0000 */
	{
		.bar = 0x0,
		.compare = 0x1200000000ULL,
		.mask = 30,
		.ep_id_size = 4,
		.ep_idx = 26,
		.table_offset = 32,
		.translate_addr = false,
		.initialized = true,
		.index = 1,
	},
	/* idx  2: Mimir SRAM / CCE        0x0_0012_8000_0000 */
	{
		.bar = 0x0,
		.compare = 0x1280000000ULL,
		.mask = 27,
		.ep_id_size = 5,
		.ep_idx = 22,
		.table_offset = 64,
		.translate_addr = false,
		.initialized = true,
		.index = 2,
	},
	/* idx  3: Mimir Config            0x0_0013_0000_0000 */
	{
		.bar = 0x0,
		.compare = 0x1300000000ULL,
		.mask = 31,
		.ep_id_size = 4,
		.ep_idx = 27,
		.table_offset = 96,
		.translate_addr = false,
		.initialized = true,
		.index = 3,
	},
	/* idx  4: TensixNeo               0x0_0100_0000_0000 */
	{
		.bar = 0x0,
		.compare = 0x10000000000ULL,
		.mask = 30,
		.ep_id_size = 6,
		.ep_idx = 24,
		.table_offset = 128,
		.translate_addr = true,
		.initialized = true,
		.index = 4,
	},
	/* idx  5: Quasar GDDR             0x1_0000_0000_0000 */
	{
		.bar = 0x800000000ULL,
		.compare = 0x1000000000000ULL,
		.mask = 38,
		.ep_id_size = 5,
		.ep_idx = 33,
		.table_offset = 96,
		.translate_addr = true,
		.initialized = true,
		.index = 5,
	},
	/* idx  6: Athena PCIE IO          0x2_0000_0000_0000 */
	{
		.bar = 0x0,
		.compare = 0x2000000000000ULL,
		.mask = 49,
		.ep_id_size = 1,
		.ep_idx = 48,
		.table_offset = 16,
		.translate_addr = false,
		.initialized = true,
		.index = 6,
	},
	/* idx  7: Athena LPDDR            0x4_0000_0000_0000 */
	{
		.bar = 0x0,
		.compare = 0x4000000000000ULL,
		.mask = 49,
		.ep_id_size = 1,
		.ep_idx = 48,
		.table_offset = 16,
		.translate_addr = false,
		.initialized = true,
		.index = 7,
	},
	/* idx  8: Keraunos PCIE IO        0x6_0000_0000_0000 */
	{
		.bar = 0x2000000000000ULL,
		.compare = 0x6000000000000ULL,
		.mask = 49,
		.ep_id_size = 1,
		.ep_idx = 48,
		.table_offset = 39,
		.translate_addr = true,
		.initialized = true,
		.index = 8,
	},
	/* idx 13: Local Alias             0x0_0000_C000_0000 */
	{
		.bar = 0x0,
		.compare = 0xC0000000ULL,
		.mask = 30,
		.ep_id_size = 0,
		.ep_idx = 30,
		.table_offset = 0,
		.translate_addr = true,
		.initialized = true,
		.index = 13,
	},
	/* idx 14: Quasar[0] Config        0x0_0018_0000_0000 */
	{
		.bar = 0x0,
		.compare = 0x1800000000ULL,
		.mask = 34,
		.ep_id_size = 6,
		.ep_idx = 28,
		.table_offset = 256,
		.translate_addr = true,
		.initialized = true,
		.index = 14,
	},
	/* idx 15: Quasar[1] Config        0x0_001C_0000_0000 */
	{
		.bar = 0x0,
		.compare = 0x1C00000000ULL,
		.mask = 34,
		.ep_id_size = 6,
		.ep_idx = 28,
		.table_offset = 320,
		.translate_addr = true,
		.initialized = true,
		.index = 15,
	},
};

#define GR_NOC2AXI_NUM_MASK_ENTRIES ARRAY_SIZE(gr_noc2axi_mask_entries)

static const struct gr_noc2axi_ep_entry gr_noc2axi_ep_entries[] = {
	/* Keraunos[0] endpoints */
	{ .index = 32,  .x_coor = 11, .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 33,  .x_coor = 11, .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 34,  .x_coor = 11, .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 35,  .x_coor = 11, .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 36,  .x_coor = 11, .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 37,  .x_coor = 11, .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 38,  .x_coor = 11, .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 39,  .x_coor = 11, .y_coor = 1, .is_self = false, .initialized = true },

	/* Mimir CCE / SRAM endpoints */
	{ .index = 64,  .x_coor = 4,  .y_coor = 7, .is_self = false, .initialized = true },
	{ .index = 65,  .x_coor = 5,  .y_coor = 7, .is_self = false, .initialized = true },
	{ .index = 66,  .x_coor = 8,  .y_coor = 7, .is_self = false, .initialized = true },
	{ .index = 67,  .x_coor = 9,  .y_coor = 7, .is_self = false, .initialized = true },
	{ .index = 68,  .x_coor = 7,  .y_coor = 0, .is_self = false, .initialized = true },
	{ .index = 69,  .x_coor = 6,  .y_coor = 0, .is_self = false, .initialized = true },
	{ .index = 70,  .x_coor = 3,  .y_coor = 0, .is_self = false, .initialized = true },
	{ .index = 71,  .x_coor = 2,  .y_coor = 0, .is_self = false, .initialized = true },

	/* Mimir Config endpoints (tile 0) */
	{ .index = 96,  .x_coor = 4,  .y_coor = 7, .is_self = false, .initialized = true },
	{ .index = 97,  .x_coor = 8,  .y_coor = 7, .is_self = false, .initialized = true },
	{ .index = 98,  .x_coor = 7,  .y_coor = 0, .is_self = false, .initialized = true },
	{ .index = 99,  .x_coor = 3,  .y_coor = 0, .is_self = false, .initialized = true },

	/* Mimir Config endpoints (tile 1) */
	{ .index = 112, .x_coor = 5,  .y_coor = 7, .is_self = false, .initialized = true },
	{ .index = 113, .x_coor = 9,  .y_coor = 7, .is_self = false, .initialized = true },
	{ .index = 114, .x_coor = 6,  .y_coor = 0, .is_self = false, .initialized = true },
	{ .index = 115, .x_coor = 2,  .y_coor = 0, .is_self = false, .initialized = true },

	/* Quasar[0] TensixNeo endpoints (ep 128-159) */
	{ .index = 128, .x_coor = 2,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 129, .x_coor = 3,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 130, .x_coor = 4,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 131, .x_coor = 5,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 132, .x_coor = 6,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 133, .x_coor = 7,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 134, .x_coor = 8,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 135, .x_coor = 9,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 136, .x_coor = 2,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 137, .x_coor = 3,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 138, .x_coor = 4,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 139, .x_coor = 5,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 140, .x_coor = 6,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 141, .x_coor = 7,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 142, .x_coor = 8,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 143, .x_coor = 9,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 144, .x_coor = 2,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 145, .x_coor = 3,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 146, .x_coor = 4,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 147, .x_coor = 5,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 148, .x_coor = 6,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 149, .x_coor = 7,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 150, .x_coor = 8,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 151, .x_coor = 9,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 152, .x_coor = 2,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 153, .x_coor = 3,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 154, .x_coor = 4,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 155, .x_coor = 5,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 156, .x_coor = 6,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 157, .x_coor = 7,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 158, .x_coor = 8,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 159, .x_coor = 9,  .y_coor = 5, .is_self = false, .initialized = true },

	/* Quasar[1] TensixNeo endpoints (ep 160-191) -- same grid pattern */
	{ .index = 160, .x_coor = 2,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 161, .x_coor = 3,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 162, .x_coor = 4,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 163, .x_coor = 5,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 164, .x_coor = 6,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 165, .x_coor = 7,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 166, .x_coor = 8,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 167, .x_coor = 9,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 168, .x_coor = 2,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 169, .x_coor = 3,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 170, .x_coor = 4,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 171, .x_coor = 5,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 172, .x_coor = 6,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 173, .x_coor = 7,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 174, .x_coor = 8,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 175, .x_coor = 9,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 176, .x_coor = 2,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 177, .x_coor = 3,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 178, .x_coor = 4,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 179, .x_coor = 5,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 180, .x_coor = 6,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 181, .x_coor = 7,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 182, .x_coor = 8,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 183, .x_coor = 9,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 184, .x_coor = 2,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 185, .x_coor = 3,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 186, .x_coor = 4,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 187, .x_coor = 5,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 188, .x_coor = 6,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 189, .x_coor = 7,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 190, .x_coor = 8,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 191, .x_coor = 9,  .y_coor = 5, .is_self = false, .initialized = true },

	/*
	 * Quasar[0] Config endpoints (ep 256-315)
	 * 8x4 Tensix grid at x=2..9, y=2..5, then peripherals
	 */
	{ .index = 256, .x_coor = 2,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 257, .x_coor = 3,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 258, .x_coor = 4,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 259, .x_coor = 5,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 260, .x_coor = 6,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 261, .x_coor = 7,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 262, .x_coor = 8,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 263, .x_coor = 9,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 264, .x_coor = 2,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 265, .x_coor = 3,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 266, .x_coor = 4,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 267, .x_coor = 5,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 268, .x_coor = 6,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 269, .x_coor = 7,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 270, .x_coor = 8,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 271, .x_coor = 9,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 272, .x_coor = 2,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 273, .x_coor = 3,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 274, .x_coor = 4,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 275, .x_coor = 5,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 276, .x_coor = 6,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 277, .x_coor = 7,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 278, .x_coor = 8,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 279, .x_coor = 9,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 280, .x_coor = 2,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 281, .x_coor = 3,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 282, .x_coor = 4,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 283, .x_coor = 5,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 284, .x_coor = 6,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 285, .x_coor = 7,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 286, .x_coor = 8,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 287, .x_coor = 9,  .y_coor = 5, .is_self = false, .initialized = true },
	/* Quasar[0] peripherals */
	{ .index = 288, .x_coor = 1,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 289, .x_coor = 1,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 290, .x_coor = 1,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 291, .x_coor = 1,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 292, .x_coor = 2,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 293, .x_coor = 3,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 294, .x_coor = 4,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 295, .x_coor = 5,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 296, .x_coor = 6,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 297, .x_coor = 7,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 298, .x_coor = 8,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 299, .x_coor = 9,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 300, .x_coor = 10, .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 301, .x_coor = 10, .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 302, .x_coor = 10, .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 303, .x_coor = 10, .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 304, .x_coor = 9,  .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 305, .x_coor = 8,  .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 306, .x_coor = 7,  .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 307, .x_coor = 6,  .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 308, .x_coor = 5,  .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 309, .x_coor = 4,  .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 310, .x_coor = 3,  .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 311, .x_coor = 2,  .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 312, .x_coor = 10, .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 313, .x_coor = 10, .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 314, .x_coor = 1,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 315, .x_coor = 1,  .y_coor = 1, .is_self = false, .initialized = true },

	/*
	 * Quasar[1] Config endpoints (ep 320-379)
	 * Same grid layout as Quasar[0]
	 */
	{ .index = 320, .x_coor = 2,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 321, .x_coor = 3,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 322, .x_coor = 4,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 323, .x_coor = 5,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 324, .x_coor = 6,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 325, .x_coor = 7,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 326, .x_coor = 8,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 327, .x_coor = 9,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 328, .x_coor = 2,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 329, .x_coor = 3,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 330, .x_coor = 4,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 331, .x_coor = 5,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 332, .x_coor = 6,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 333, .x_coor = 7,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 334, .x_coor = 8,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 335, .x_coor = 9,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 336, .x_coor = 2,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 337, .x_coor = 3,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 338, .x_coor = 4,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 339, .x_coor = 5,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 340, .x_coor = 6,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 341, .x_coor = 7,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 342, .x_coor = 8,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 343, .x_coor = 9,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 344, .x_coor = 2,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 345, .x_coor = 3,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 346, .x_coor = 4,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 347, .x_coor = 5,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 348, .x_coor = 6,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 349, .x_coor = 7,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 350, .x_coor = 8,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 351, .x_coor = 9,  .y_coor = 5, .is_self = false, .initialized = true },
	/* Quasar[1] peripherals */
	{ .index = 352, .x_coor = 1,  .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 353, .x_coor = 1,  .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 354, .x_coor = 1,  .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 355, .x_coor = 1,  .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 356, .x_coor = 2,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 357, .x_coor = 3,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 358, .x_coor = 4,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 359, .x_coor = 5,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 360, .x_coor = 6,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 361, .x_coor = 7,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 362, .x_coor = 8,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 363, .x_coor = 9,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 364, .x_coor = 10, .y_coor = 5, .is_self = false, .initialized = true },
	{ .index = 365, .x_coor = 10, .y_coor = 4, .is_self = false, .initialized = true },
	{ .index = 366, .x_coor = 10, .y_coor = 3, .is_self = false, .initialized = true },
	{ .index = 367, .x_coor = 10, .y_coor = 2, .is_self = false, .initialized = true },
	{ .index = 368, .x_coor = 9,  .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 369, .x_coor = 8,  .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 370, .x_coor = 7,  .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 371, .x_coor = 6,  .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 372, .x_coor = 5,  .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 373, .x_coor = 4,  .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 374, .x_coor = 3,  .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 375, .x_coor = 2,  .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 376, .x_coor = 1,  .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 377, .x_coor = 10, .y_coor = 6, .is_self = false, .initialized = true },
	{ .index = 378, .x_coor = 10, .y_coor = 1, .is_self = false, .initialized = true },
	{ .index = 379, .x_coor = 1,  .y_coor = 1, .is_self = false, .initialized = true },
};

#define GR_NOC2AXI_NUM_EP_ENTRIES ARRAY_SIZE(gr_noc2axi_ep_entries)

#define GR_NOC2AXI_MIMIR_CCE_EP_START  64
#define GR_NOC2AXI_MIMIR_CCE_EP_END    79
#define GR_NOC2AXI_MIMIR_CFG_EP_START  96
#define GR_NOC2AXI_MIMIR_CFG_EP_END    103

#endif /* GRENDEL_NOC2AXI_DATA_H */
